# Generated by Django 4.2.11 on 2024-05-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0004_rename_id_vendors_vender_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='average_response_time',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='fulfillment_rate',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='on_time_delivery_rate',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='quality_rating_avg',
        ),
    ]
