# Generated by Django 4.2.11 on 2024-05-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase_Orders', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
    ]
